# Generated by Django 4.2.6 on 2024-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
