# Generated by Django 4.2.6 on 2024-01-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_roomdetailmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomDetailModel',
        ),
    ]
