# Generated by Django 4.2.6 on 2024-01-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_roomdetailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.roommodel')),
            ],
        ),
    ]
